import { ExpenseCategoriesType, TransactionType } from "@/types";
import * as Icons from "phosphor-react-native";

export const expenseCategories: ExpenseCategoriesType = {
  groceries: {
    label: "Courses",
    value: "groceries",
    icon: Icons.ShoppingCartIcon,
    bgColor: "#4B5563",
  },
  food: {
    label: "Alimentation",
    value: "food",
    icon: Icons.ForkKnifeIcon,
    bgColor: "#be185d",
  },
  rent: {
    label: "Loyer",
    value: "rent",
    icon: Icons.HouseIcon,
    bgColor: "#075985",
  },
  utilities: {
    label: "Factures & Services",
    value: "utilities",
    icon: Icons.LightbulbIcon,
    bgColor: "#ca8a04",
  },
  transportation: {
    label: "Transport",
    value: "transportation",
    icon: Icons.CarIcon,
    bgColor: "#b45309",
  },
  transport: {
    label: "Transport",
    value: "transport",
    icon: Icons.CarIcon,
    bgColor: "#b45309",
  },
  entertainment: {
    label: "Divertissement",
    value: "entertainment",
    icon: Icons.FilmStripIcon,
    bgColor: "#0f766e",
  },
  dining: {
    label: "Restaurant",
    value: "dining",
    icon: Icons.ForkKnifeIcon,
    bgColor: "#be185d",
  },
  health: {
    label: "Santé",
    value: "health",
    icon: Icons.HeartIcon,
    bgColor: "#e11d48",
  },
  insurance: {
    label: "Assurance",
    value: "insurance",
    icon: Icons.ShieldCheckIcon,
    bgColor: "#404040",
  },
  savings: {
    label: "Épargne",
    value: "savings",
    icon: Icons.PiggyBankIcon,
    bgColor: "#065F46",
  },
  clothing: {
    label: "Vêtements",
    value: "clothing",
    icon: Icons.TShirtIcon,
    bgColor: "#7c3aed",
  },
  shopping: {
    label: "Shopping",
    value: "shopping",
    icon: Icons.BagIcon,
    bgColor: "#9333ea",
  },
  subscriptions: {
    label: "Abonnements",
    value: "subscriptions",
    icon: Icons.CreditCardIcon,
    bgColor: "#2563eb",
  },
  personal: {
    label: "Personnel",
    value: "personal",
    icon: Icons.UserIcon,
    bgColor: "#a21caf",
  },
  others: {
    label: "Autres",
    value: "others",
    icon: Icons.DotsThreeOutlineIcon,
    bgColor: "#525252",
  },
};

export const incomeCategories: ExpenseCategoriesType = {
  salary: {
    label: "Salaire",
    value: "salary",
    icon: Icons.MoneyIcon,
    bgColor: "#16a34a",
  },
  freelance: {
    label: "Freelance",
    value: "freelance",
    icon: Icons.BriefcaseIcon,
    bgColor: "#059669",
  },
  gift: {
    label: "Cadeau",
    value: "gift",
    icon: Icons.GiftIcon,
    bgColor: "#10b981",
  },
  others: {
    label: "Autres revenus",
    value: "others",
    icon: Icons.CurrencyDollarSimpleIcon,
    bgColor: "#047857",
  },
};

export const transactionTypes = [
  { label: "Dépense", value: "expense" },
  { label: "Revenu", value: "income" },
];

export const mockTransactions: TransactionType[] = [
  {
    id: "1",
    type: "income",
    amount: 2200,
    category: "salary",
    date: new Date("2026-06-01"),
    description: "Salaire mensuel",
    walletId: "wallet_1",
  },
  {
    id: "2",
    type: "expense",
    amount: 650,
    category: "rent",
    date: new Date("2026-06-02"),
    description: "Loyer appartement",
    walletId: "wallet_1",
  },
  {
    id: "3",
    type: "expense",
    amount: 45.5,
    category: "food",
    date: new Date("2026-06-03"),
    description: "Courses hebdomadaires Carrefour",
    walletId: "wallet_1",
  },
  {
    id: "4",
    type: "expense",
    amount: 15,
    category: "transport",
    date: new Date("2026-06-04"),
    description: "Ticket de métro / Bus",
    walletId: "wallet_1",
  },
  {
    id: "5",
    type: "expense",
    amount: 25,
    category: "utilities",
    date: new Date("2026-06-05"),
    description: "Facture internet fibre",
    walletId: "wallet_1",
  },
  {
    id: "6",
    type: "income",
    amount: 120,
    category: "freelance",
    date: new Date("2026-06-06"),
    description: "Mission freelance design",
    walletId: "wallet_1",
  },
  {
    id: "7",
    type: "expense",
    amount: 32.9,
    category: "entertainment",
    date: new Date("2026-06-07"),
    description: "Restaurant entre amis",
    walletId: "wallet_1",
  },
  {
    id: "8",
    type: "expense",
    amount: 12.99,
    category: "subscriptions",
    date: new Date("2026-06-08"),
    description: "Abonnement Netflix",
    walletId: "wallet_1",
  },
  {
    id: "9",
    type: "expense",
    amount: 50,
    category: "shopping",
    date: new Date("2026-06-09"),
    description: "Achat t-shirts et chemise",
    walletId: "wallet_1",
  },
  {
    id: "10",
    type: "expense",
    amount: 18.5,
    category: "food",
    date: new Date("2026-06-10"),
    description: "Boulangerie et petits déjeuners",
    walletId: "wallet_1",
  },
  {
    id: "11",
    type: "income",
    amount: 50,
    category: "gift",
    date: new Date("2026-06-10"),
    description: "Remboursement d'un ami",
    walletId: "wallet_1",
  },
  {
    id: "12",
    type: "expense",
    amount: 45,
    category: "transport",
    date: new Date("2026-06-11"),
    description: "Plein d'essence",
    walletId: "wallet_1",
  },
  {
    id: "13",
    type: "expense",
    amount: 89,
    category: "health",
    date: new Date("2026-06-12"),
    description: "Visite chez le médecin traitant",
    walletId: "wallet_1",
  },
  {
    id: "14",
    type: "expense",
    amount: 10,
    category: "entertainment",
    date: new Date("2026-06-13"),
    description: "Cinéma place de séance",
    walletId: "wallet_1",
  },
  {
    id: "15",
    type: "expense",
    amount: 72.4,
    category: "food",
    date: new Date("2026-06-14"),
    description: "Supermarché bio",
    walletId: "wallet_1",
  },
  {
    id: "16",
    type: "income",
    amount: 300,
    category: "freelance",
    date: new Date("2026-06-15"),
    description: "Vente d'un ancien meuble",
    walletId: "wallet_1",
  },
  {
    id: "17",
    type: "expense",
    amount: 9.99,
    category: "subscriptions",
    date: new Date("2026-06-16"),
    description: "Spotify Premium",
    walletId: "wallet_1",
  },
  {
    id: "18",
    type: "expense",
    amount: 35,
    category: "utilities",
    date: new Date("2026-06-17"),
    description: "Facture d'électricité",
    walletId: "wallet_1",
  },
  {
    id: "19",
    type: "expense",
    amount: 22,
    category: "entertainment",
    date: new Date("2026-06-18"),
    description: "Bar / Sortie afterwork",
    walletId: "wallet_1",
  },
  {
    id: "20",
    type: "expense",
    amount: 14.5,
    category: "food",
    date: new Date("2026-06-19"),
    description: "Sandwich et café du midi",
    walletId: "wallet_1",
  },
  {
    id: "21",
    type: "income",
    amount: 75,
    category: "gift",
    date: new Date("2026-06-20"),
    description: "Cadeau d'anniversaire de la famille",
    walletId: "wallet_1",
  },
  {
    id: "22",
    type: "expense",
    amount: 60,
    category: "shopping",
    date: new Date("2026-06-21"),
    description: "Achat d'un livre et matériel",
    walletId: "wallet_1",
  },
  {
    id: "23",
    type: "expense",
    amount: 28,
    category: "transport",
    date: new Date("2026-06-22"),
    description: "Abonnement de bus mensuel",
    walletId: "wallet_1",
  },
  {
    id: "24",
    type: "expense",
    amount: 19.99,
    category: "subscriptions",
    date: new Date("2026-06-23"),
    description: "Cloud Storage et applications",
    walletId: "wallet_1",
  },
  {
    id: "25",
    type: "expense",
    amount: 42.3,
    category: "food",
    date: new Date("2026-06-24"),
    description: "Marché local du samedi",
    walletId: "wallet_1",
  },
];
